<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Анализатор страниц</title>
  </head>

  <body class="min-vh-100 container-fluid p-0">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid px-3">
          <a class="navbar-brand" href="/">Анализатор страниц</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/">Главная</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/urls">Сайты</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="row container-fluid px-0 mx-0">
      <?php if (isset($flash)) : ?>
        <div class="d-none d-sm-block alert alert-success" role="alert">
          <?= $flash ?>
        </div>
        <div class="d-sm-none text-center alert alert-success mb-2" role="alert">
          <?= $flash ?>
        </div>
      <?php endif; ?>
      <div class="col-md-8 col-sm-10 col-12 mx-auto mt-sm-3 mt-2">
        <h1 class="d-none d-sm-block">Сайт: <?= $url['name'] ?></h1>
        <h1 class="d-sm-none text-center">Сайт: <?= $url['name'] ?></h1>
      </div>
      <div class="col-md-8 col-sm-10 col-12 mx-auto mt-2 mb-sm-5 mb-0">
        <table class="table table-bordered" data-test="url">
          <tbody>
            <tr class="d-none d-sm-table-row">
              <th scope="row">ID</th>
              <td><?= $url['id'] ?></td>
            </tr>
            <tr class="d-sm-none small">
              <th scope="row">ID</th>
              <td><?= $url['id'] ?></td>
            </tr>
            <tr class="d-none d-sm-table-row">
              <th scope="row">Имя</th>
              <td><?= $url['name'] ?></td>
            </tr>
            <tr class="d-sm-none small">
              <th scope="row">Имя</th>
              <td><?= $url['name'] ?></td>
            </tr>
            <tr class="d-none d-sm-table-row">
              <th scope="row">Дата создания</th>
              <td><?= $url['created_at'] ?></td>
            </tr>
            <tr class="d-sm-none small">
              <th scope="row">Дата создания</th>
              <td><?= $url['created_at'] ?></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="d-none d-sm-block col-md-8 col-10 mx-auto mb-3">
        <h2>Проверки</h2>
        <form class="mt-3" action="/urls/<?= $url['id'] ?>/checks" method="post">
          <input class="btn btn-primary btn-md" type="submit" value="Запустить проверку">
        </form>
      </div>
      <div class="d-sm-none col-12 mx-auto mb-3">
        <h2 class="text-center">Проверки</h2>
        <div class="col-6 mt-3 mx-auto">
          <form action="/urls/<?= $url['id'] ?>/checks" method="post">
            <input class="btn btn-primary btn-md col-12" type="submit" value="Запустить проверку">
          </form>
        </div>
      </div>
      <div class="col-md-8 col-sm-10 col-12 mx-auto">
        <table class="table table-bordered table-striped table-hover" data-test="checks">
          <thead class="table-dark">
            <tr class="d-none d-sm-table-row">
              <th>ID</th>
              <th>Код ответа</th>
              <th>h1</th>
              <th>title</th>
              <th>description</th>
              <th>Дата создания</th>
            </tr>
            <tr class="d-sm-none small">
              <th>ID</th>
              <th>Код ответа</th>
              <th>h1</th>
              <th>title</th>
              <th>description</th>
              <th>Дата создания</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($checks as $row) : ?>
              <tr class="d-none d-sm-table-row">
                <td>
                  <?= $row['id'] ?>
                </td>
                <td>
                  <?= $row['status_code'] ?>
                </td>
                <td>
                  <?= $row['h1'] ?>
                </td>
                <td>
                  <?= $row['title'] ?>
                </td>
                <td>
                  <?= $row['description'] ?>
                </td>
                <td>
                  <?= $row['created_at'] ?>
                </td>
              </tr>
              <tr class="d-sm-none small">
                <td>
                  <?= $row['id'] ?>
                </td>
                <td>
                  <?= $row['status_code'] ?>
                </td>
                <td>
                  <?= $row['h1'] ?>
                </td>
                <td>
                  <?= $row['title'] ?>
                </td>
                <td>
                  <?= $row['description'] ?>
                </td>
                <td>
                  <?= $row['created_at'] ?>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    </main>

    <footer class="fixed-bottom">
      <div class="container-fluid">
        <div class="row border-top py-3 text-center">
          <a href="https://hexlet.io/pages/about">Hexlet</a>
        </div>
      </div>
    </footer>
    <!-- пакет Bootstrap с Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>