<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Анализатор страниц</title>
  </head>

  <body class="min-vh-100 container-fluid p-0">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid px-3">
          <a class="navbar-brand" href="/">Анализатор страниц</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Главная</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/urls">Сайты</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="row container-fluid px-0 mx-0">
      <!-- Для больших экранов -->
      <div class="d-none d-lg-block col-xxl-6 col-xl-7 col-8 mx-auto my-3 px-0">
        <div class="container-fluid border rounded bg-light p-0">
          <div class="row m-5 mb-0">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
          </div>
          <form class="row m-5 mt-0" action="/urls" method="post">
            <?php if (isset($error)): ?>
              <div class="col">
                <input class="form-control form-control-lg is-invalid" type="text" value="<?= htmlspecialchars($name) ?>" name="url[name]">
                <div class="invalid-feedback">
                  <p><?= $error ?></p>
                </div>
              </div>
              <div class="col-auto">
                <input class="btn btn-primary btn-lg px-5 text-uppercase" type="submit" value="Проверить">
              </div>
            <?php else: ?>
              <div class="col">
                <input class="form-control form-control-lg" type="text" placeholder="https://example.com" name="url[name]">
              </div>
              <div class="col-auto">
                <input class="btn btn-primary btn-lg px-5 text-uppercase" type="submit" value="Проверить">
              </div>
            <?php endif; ?>
          </form>
        </div>
      </div>
    <footer class="fixed-bottom">
      <div class="container-fluid">
        <div class="row border-top py-3 text-center">
          <a href="https://hexlet.io/pages/about">Hexlet</a>
        </div>
      </div>
    </footer>
    <!-- пакет Bootstrap с Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>