<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Анализатор страниц</title>
  </head>

  <body class="min-vh-100 d-flex flex-column">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid px-3">
          <a class="navbar-brand" href="/">Анализатор страниц</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="/">Главная</a>
              <a class="nav-link" href="/urls">Сайты</a>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="flex-fill">
      <!-- Для больших экранов -->
      <div class="d-none d-lg-block col-xxl-6 col-xl-7 col-8 mx-auto my-3">
        <div class="container-fluid p-5 border rounded bg-light">
          <h1 class="display-3">Анализатор страниц</h1>
          <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
          <form class="d-flex flex-row" action="/urls" method="post">
            <input class="form-control form-control-lg" type="text" placeholder="https://example.com" name="url">
              <div class="mx-5 my-0">
                <input class="btn btn-primary btn-lg px-5 text-uppercase" type="submit" value="Проверить">
              </div>
          </form>
        </div>
      </div>

      <!-- Для средних и маленьких экранов-->
      <div class="d-lg-none col-md-10 col-12 mx-auto my-3">
        <div class="container-fluid p-md-3 p-auto border rounded bg-light text-center">
          <h1 class="display-4">Анализатор страниц</h1>
          <p class="lead" style="font-size: 1rem">Бесплатно проверяйте сайты на SEO пригодность</p>
          <form class="d-flex flex-md-row flex-column" action="/urls" method="post">
            <input class="form-control" type="text" placeholder="https://example.com" name="url">
              <div class="align-self-center mx-md-3 mx-0 my-md-0 my-3">
                <input class="btn btn-primary btn-md px-4 text-uppercase" type="submit" value="Проверить">
              </div>
          </form>
        </div>
      </div>
    </main>

    <footer>
      <div class="container-fluid">
        <div class="row border-top py-3 text-center">
          <a href="https://hexlet.io/pages/about">Hexlet</a>
        </div>
      </div>
    </footer>
    <!-- пакет Bootstrap с Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>