<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Анализатор страниц</title>
  </head>

  <body class="min-vh-100 container-fluid p-0">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid px-3">
          <a class="navbar-brand" href="/">Анализатор страниц</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/">Главная</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/urls">Сайты</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="row container-fluid px-0 mx-0">
      <div class="col-md-8 col-sm-10 col-12 mx-auto mt-sm-3 mt-2">
        <h1 class="d-none d-sm-block">Сайты</h1>
        <h1 class="d-sm-none text-center">Сайты</h1>
      </div>
      <div class="col-md-8 col-sm-10 col-12 mx-auto">
        <table class="table table-bordered table-hover">
          <thead class="table-dark" data-test="urls">
            <tr class="d-none d-sm-table-row">
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
            <tr class="d-sm-none small">
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($table as $row) : ?>
              <tr class="d-none d-sm-table-row">
                <th scope="row">
                  <?= $row['id'] ?>
                </th>
                <td>
                  <a href="/urls/<?= $row['id'] ?>">
                    <?= $row['name'] ?>
                  </a>
                </td>
                <td>
                  <?= isset($row['created_at']) ? $row['created_at'] : null ?>
                </td>
                <td>
                  <?= isset($row['status_code']) ? $row['status_code'] : null ?>
                </td>
              </tr>
              <tr class="d-sm-none small">
                <th scope="row">
                  <?= $row['id'] ?>
                </th>
                <td>
                  <a href="/urls/<?= $row['id'] ?>">
                    <?= $row['name'] ?>
                  </a>
                </td>
                <td>
                  <?= $row['created_at'] ?>
                </td>
                <td>
                  <?= $row['status_code'] ?>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    </main>

    <footer class="fixed-bottom">
      <div class="container-fluid">
        <div class="row border-top py-3 text-center">
          <a href="https://hexlet.io/pages/about">Hexlet</a>
        </div>
      </div>
    </footer>
    <!-- пакет Bootstrap с Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>